pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

Properties properties = new Properties()
File propertiesFile = new File('local.properties')
propertiesFile.withInputStream {
    properties.load(it)
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        maven {
            name = "GitHubPackages"
            url = uri("https://github.com/radixdlt/maven-pkg/packages/")
            credentials {
                username = properties.getProperty("GPR_USER")
                password = properties.getProperty("GPR_TOKEN")
            }
        }
        maven { url 'https://jitpack.io' }
    }

}
rootProject.name = "BabylonWallet"
include ':app'
include ':peerdroid'
include ':webrtc-library'
include ':designsystem'
include ':profile'
include ':core'
